import React from "react";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import { sanityClient } from "../../sanity";
import { urlFor } from "../../sanity";
import Head from "next/head";
import Link from "next/link";

function BlogPage({ posts }) {
  console.log(posts);
  return (
    <>
      <Navbar />
      <Head>
        <title>Agency Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-6xl mx-auto grid py-[7rem]">
        <h1 className="text-center text-4xl font-bold">Agency Blog Page</h1>
        <div className="grid grid-cols-1  p-6 sm:grid-cols-2  lg:grid-cols-3 gap-6  md:grid-cols-3 md:gap-10 md:p-6">
          {posts.map((post) => (
            <Link key={post._id} href={`/post/${post.slug.current}`}>
              <div className="group cursor-pointer  border border-gray-300  rounded-lg overflow-hidden h-auto  hover:shadow-xl h-[20rem]">
                <img
                  className=" h-[10rem] w-full object-cover group-hover:scale-105 transition-transform duration-200 ease-in-out"
                  src={urlFor(post.mainImage).url()}
                  alt="blogMainImage"
                />
                <div className="px-5 py-5 bg-white ">
                  <h1 className="font-bold uppercase text-md">{post.title}</h1>
                  <p className="text-gray-400 mb-5 md:text-sm">
                    {" "}
                    {post.descriptionpost}
                  </p>
                  <div className="flex  items-center justify-center md:justify-start  space-x-5">
                    <img
                      className="w-12 h-12 rounded-lg"
                      src={urlFor(post.author.image).url()}
                      alt="authorImage"
                    />
                    <p className="text-sm">by {post.author.name}</p>
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </main>
      <Footer />
    </>
  );
}

export default BlogPage;

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const query = `*[_type == "post"]{
    _id,
    title,
    author -> {
      name, 
      image
    },
    slug,
    descriptionpost,
    mainImage,
    publishedAt
  }`;

  const posts = await sanityClient.fetch(query);

  // Pass data to the page via props
  return {
    props: {
      posts,
    },
  };
}
