import Head from "next/head";
import Feature from "../components/Feature";
import Future from "../components/Future";
import Help from "../components/Help";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Purpose from "../components/Purpose";
import Sponsored from "../components/Sponsored";

export default function Home() {
  const featureData = [
    {
      title: "Great customer relationship starts here",
      desc: "Schedule",
      para: "80 days around the world, well find a pot of gold just sitting where the rainbows ending. Time — well fight against the time, and well fly on the white wings of the wind.",
      more: "Learn more about publishing",
      imgSrc: "/assets/card-carousel.png",
      more: "Learn more about publishing",
    },
  ];
  return (
    <div className="">
      <Head>
        <title>Agency Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* HOME LANDING */}
        <Navbar />
        <Hero />
        <Sponsored />
        {/* ========== */}
        <Purpose />
        <Help />

        <div className="m-w-3xl mx-auto md:flex  md:items-center">
          <Feature
            imgSrc={"/assets/card-carousel.png"}
            desc={"Schedule"}
            title={"Great customer relationship starts here"}
            para={
              "80 days around the world, well find a pot of gold just sitting where the rainbows ending. Time — well fight against the time, and well fly on the white wings of the wind."
            }
            more={"Learn more about publishing"}
          />
        </div>
        {/* Versi mapping  */}
        <div className="m-w-3xl mx-auto md:flex md:flex-row-reverse  md:items-center">
          {featureData.map((data) => (
            <Feature
              title={data.title}
              imgSrc={data.imgSrc}
              desc={data.desc}
              para={data.para}
              more={data.more}
            />
          ))}
        </div>

        <Future />
      </main>
    </div>
  );
}
