import Head from "next/head";
import Feature from "../components/Feature";
import Footer from "../components/Footer";
import Future from "../components/Future";
import Help from "../components/Help";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Purpose from "../components/Purpose";
import Sponsored from "../components/Sponsored";
import Testimonial from "../components/Testimonial";

export default function Home() {
  const featureData = [
    {
      title: "Introducing best mobile carousels",
      desc: "Monitor",
      para: "Before the ship is really back. Round, round, all around the world. Round, all around the world. Round, all around the world. Round, all around the world.",
      imgSrc: "/assets/card-customer.png",
      more: "Learn more about monitor",
    },
  ];
  return (
    <div className="">
      <Head>
        <title>Agency Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* HOME LANDING */}
        <Navbar />
        <Hero />
        <Sponsored />
        {/* ========== */}
        <Purpose />
        <Help />

        <div className="max-w-6xl mx-auto md:flex  md:items-center">
          <Feature
            imgSrc={"/assets/card-carousel.png"}
            desc={"Schedule"}
            title={"Great customer relationship starts here"}
            para={
              "80 days around the world, well find a pot of gold just sitting where the rainbows ending. Time — well fight against the time, and well fly on the white wings of the wind."
            }
            more={"Learn more about publishing"}
          />
        </div>
        {/* Versi mapping  */}
        <div className="max-w-6xl mx-auto md:flex md:flex-row-reverse  md:items-center">
          {featureData.map((data) => (
            <Feature
              key={data.desc}
              title={data.title}
              imgSrc={data.imgSrc}
              desc={data.desc}
              para={data.para}
              more={data.more}
            />
          ))}
        </div>
        <Future />
        <Testimonial />
        <Footer />
      </main>
    </div>
  );
}
